# see https://github.com/karlicoss/pymplate for up-to-date reference
[project]
dynamic = ["version"]  # version is managed by setuptools_scm
name = "axol"
dependencies = [
    "click",
    "loguru",
    "orjson",
    "sqlalchemy",
    "more-itertools",
    "typing-extensions",
    "tabulate",  # for configs listing
]

## these need to be set if you're planning to upload to pypi
description = "Your personal search alerts"
license = {file = "LICENSE"}
authors = [
    {name = "Dima Gerasimov (@karlicoss)", email = "karlicoss@gmail.com"},
]
maintainers = [
    {name = "Dima Gerasimov (@karlicoss)", email = "karlicoss@gmail.com"},
]


[project.urls]
Homepage = "https://github.com/karlicoss/axol"
##

[project.optional-dependencies]
optional = [
    "PyGithub",        # modules.github.search
    "python-hn",       # modules.hackernews.search
    "praw",            # modules.reddit.search
    "beautifulsoup4",  # modules.lobsters.search
    "html2text"     ,  # for rendering (e.g. to markdown)
]
testing = [
    "pytest",
    "ruff",
    "mypy",
    "lxml",  # for mypy html coverage
]


[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "dirty-tag"
