#!/bin/bash
set -eu

cd "$(dirname "$0")"
cd .. # git root

if ! command -v sudo; then
    # CI or Docker sometimes doesn't have it, so useful to have a dummy
    function sudo {
        "$@"
    }
fi

# --parallel-live to show outputs while it's running
tox_cmd='run-parallel --parallel-live'
if [ -n "${CI-}" ]; then
    # install OS specific stuff here
    case "$OSTYPE" in
    darwin*) 
        # macos
        :
        ;;
    cygwin* | msys* | win*)
        # windows
        :
        ;;
    *)
        # must be linux?
        :
        ;;
    esac
fi

# NOTE: expects uv installed
uv tool run --with tox-uv tox $tox_cmd "$@"
